# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: CORS Regex Plugin

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/liquidlogiclabs/traefik-plugin-cors-regex

# A brief description of what your plugin is doing.
summary: A Traefik plugin that adds support for regex and wildcard domains in the Access-Control-Allow-Origin header for CORS (Cross-Origin Resource Sharing).

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  allowOriginList:
    - "https://example.com"
    - "https://*.example.com"
    - "https://api.example.org"
  allowMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowHeaders:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
  exposeHeaders:
    - "X-Custom-Header"
  allowCredentials: true
  maxAge: 86400
  debug: false