# Traefik Plugin Manifest
# This file is required for the plugin to be recognized by the Traefik Plugin Catalog

# Plugin metadata
name: cors-regex
displayName: CORS Regex Plugin
description: A Traefik plugin that adds support for regex and wildcard domains in the Access-Control-Allow-Origin header for CORS (Cross-Origin Resource Sharing).
author: LiquidLogicLabs
repository: https://github.com/liquidlogiclabs/traefik-plugin-cors-regex
homepage: https://github.com/liquidlogiclabs/traefik-plugin-cors-regex
license: MIT
tags:
  - cors
  - middleware
  - security
  - regex
  - wildcard

# Plugin type
type: middleware

# Test data for the plugin catalog
testData:
  config:
    allowOriginList:
      - "https://example.com"
      - "https://*.example.com"
      - "https://api.example.org"
    allowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowHeaders:
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "Authorization"
    exposeHeaders:
      - "X-Custom-Header"
    allowCredentials: true
    maxAge: 86400

# Plugin configuration schema
schema:
  type: object
  properties:
    allowOriginList:
      type: array
      items:
        type: string
      description: List of allowed origins (supports wildcards and regex)
    allowMethods:
      type: array
      items:
        type: string
      description: Allowed HTTP methods
    allowHeaders:
      type: array
      items:
        type: string
      description: Allowed request headers
    exposeHeaders:
      type: array
      items:
        type: string
      description: Headers to expose to the client
    allowCredentials:
      type: boolean
      description: Whether to allow credentials
    maxAge:
      type: integer
      description: Maximum age for preflight requests (in seconds)
  required: []
