version: '3.8'

services:
  # Test application
  test-app:
    image: nginx:alpine
    container_name: test-app
    ports:
      - "8991:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik-network

  # Traefik with our plugin
  traefik:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traefik-with-cors-plugin
    ports:
      - "8989:80"
      - "8990:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - traefik-network
    depends_on:
      - test-app
    environment:
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=cors-regex"
      - "traefik.http.middlewares.cors-regex.plugin.cors-regex.alloworiginlist=https://example.com,https://*.example.com,https://api.example.org"
      - "traefik.http.middlewares.cors-regex.plugin.cors-regex.allowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors-regex.plugin.cors-regex.allowheaders=Origin,Content-Type,Accept,Authorization"
      - "traefik.http.middlewares.cors-regex.plugin.cors-regex.allowcredentials=true"
      - "traefik.http.middlewares.cors-regex.plugin.cors-regex.maxage=86400"

networks:
  traefik-network:
    driver: bridge
