# Dynamic configuration for testing the CORS regex plugin
http:
  middlewares:
    cors-regex:
      plugin:
        cors-regex:
          allowOriginList:
            - "https://example.com"
            - "https://*.example.com"
            - "https://api.example.org"
            - "https://.*\\.test\\.com"
          allowMethods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
          allowHeaders:
            - "Origin"
            - "Content-Type"
            - "Accept"
            - "Authorization"
          exposeHeaders:
            - "X-Custom-Header"
          allowCredentials: true
          maxAge: 86400

  routers:
    test-api:
      rule: "Host(`localhost`) && PathPrefix(`/api`)"
      service: test-service
      middlewares:
        - cors-regex
      tls: {}

  services:
    test-service:
      loadBalancer:
        servers:
          - url: "http://test-app:8080"
