# Traefik configuration for testing the CORS regex plugin
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard
api:
  dashboard: true
  insecure: true

# Entry points
entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8080"

# Providers
providers:
  file:
    directory: /etc/traefik/conf
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# Experimental features (required for plugins)
experimental:
  plugins:
    cors-regex:
      modulename: github.com/liquidlogiclabs/traefik-plugin-cors-regex
      version: v0.1.0

# Logging
log:
  level: INFO

# Access logs
accessLog: {}
